### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by bjorkgard** [translation/laravel#17]
Is it possible to get support for Laravel 8?

**Comment by MichaelHoste** [comment]
We just released the [version 1.11](https://github.com/translation/laravel/releases/tag/v1.11) that should be compatible with Laravel 8.

Could you please confirm that it works smoothly?

Thanks for the heads up!

**Comment by bjorkgard** [comment]
A fresh installation of Laravel 8 require Guzzle v7

tio/laravel v1.11 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

**Comment by MichaelHoste** [comment]
Sorry about that! 

We relaxed the Guzzle dependency and made sure that was not an issue anymore in [Version 1.12](https://github.com/translation/laravel/releases/tag/v1.12)

**Comment by bjorkgard** [comment]
Thanks.
Works on a clean install of Laravel 8.

But if you install Laravel Jetstream, neither init nor sync works.

Error Message: InvalidArgumentException Unable to locate a class or view for component [jet -....].
None of the jetstream components need to be searched.

**Comment by MichaelHoste** [comment]
> Works on a clean install of Laravel 8.

Great! Thank you for your useful feedback 😄 

> Error Message: InvalidArgumentException Unable to locate a class or view for component [jet -....].

It seems that the component called is not present in its correct directory (see [here](https://laracasts.com/discuss/channels/laravel/laravel-7-view-component?page=1#reply=589454)).

Are you sure that this error is related to this package? Does the app works correctly without triggering the same error?

> None of the jetstream components need to be searched.

By default, the whole `app` and `resources` folders are searched for GetText strings: https://github.com/translation/laravel/blob/master/config/translation.php#L28

You can override this configuration to only allow some of your directories, but it should not trigger any error anyway.

**Comment by bjorkgard** [comment]
Yes, the app works as intended.
It is a new laravel installation with the extension for jetstream. (laravel new [name] --jet).

**Comment by MichaelHoste** [comment]
I reopened this issue and we'll investigate on what went wrong. Thanks again for your useful feedback.

I'll keep you in touch soon.

**Comment by MichaelHoste** [comment]
We located the error and created a pull request to fix it: https://github.com/php-gettext/Gettext/pull/261

I hope that it will make sense and be merged soon.

In the meantime, you can fix this by updating the `gettext_parse_paths` to avoid blade files with jet components.

Thanks for your help!

**Comment by thanosalexander** [comment]
> > Works on a clean install of Laravel 8.
> 
> Great! Thank you for your useful feedback 😄
> 
> > Error Message: InvalidArgumentException Unable to locate a class or view for component [jet -....].
> 
> It seems that the component called is not present in its correct directory (see [here](https://laracasts.com/discuss/channels/laravel/laravel-7-view-component?page=1#reply=589454)).
> 
> Are you sure that this error is related to this package? Does the app works correctly without triggering the same error?
> 
> > None of the jetstream components need to be searched.
> 
> By default, the whole `app` and `resources` folders are searched for GetText strings: https://github.com/translation/laravel/blob/master/config/translation.php#L28
> 
> You can override this configuration to only allow some of your directories, but it should not trigger any error anyway.

I noticed that when i use components namespaces https://laravel.com/docs/8.x/blade#manually-registering-package-components

like here ```<x-client::page.title />```  it gives me this error `Unable to locate a class or view for component`

**Comment by MichaelHoste** [comment]
This seems to be the same issue that we fixed in this pull request: https://github.com/php-gettext/Gettext/pull/261

I hope it will be merged soon.

**Comment by thanosalexander** [comment]
Cool.. i'll watch it Michaël . Thanks!

**Comment by MichaelHoste** [comment]
php-gettext/Gettext#261 was merged and released.

I already bumped this package to force the new version. So if you update it, it should finally work without parsing errors for Component Tags 🎉
