### ISSUE TITLE
Folder "app" doest not exists. Gettext scan aborted.

### ISSUE THREAD

**Issue by smares** [translation/laravel#19]
With a vanilla Laravel 8.10.0 project, I am getting the following error when calling `translation:init`

```
Init started

   Exception

  Folder "app" doest not exists. Gettext scan aborted.

  at /var/www/project/vendor/tio/laravel/src/GettextPOGenerator.php:52
     48▕
     49▕         // Extract GetText strings from project
     50▕         foreach ($directories as $dir) {
     51▕             if (!is_dir($dir)) {
  ➜  52▕                 throw new \Exception('Folder "' . $dir . '" doest not exists. Gettext scan aborted.');
     53▕             }
     54▕
     55▕             foreach ($this->scanDir($dir) as $file) {
     56▕                 if (strstr($file, '.blade.php')) {

      +18 vendor frames
  19  /var/www/project/artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

The config which directories to scan is unchanged with `'gettext_parse_paths' => ['app', 'resources'],`

**Comment by MichaelHoste** [comment]
Hi @smares,

I'll ask a very stupid question but... does your `/var/www/project` folder contains an `app` folder ?
I don't understand why this error would occur otherwise.

**Comment by smares** [comment]
Of course it does. 😄  app also contains the regular subfolders of a Laravel installation such as Console. Exceptions, Http, Models and Providers with them also being populated accordingly with Controllers, Middlewares and whatnot.

Edit: Oh, and btw, there's a typo in the error in the word "doest".

**Comment by MichaelHoste** [comment]
Ok, thank you for this useful precision 😄 

I don't understand it but we'll investigate by creating a fresh Laravel 8.10 project. In the meantime could you just try to print the $dir variable in the package just before the error is triggered? Maybe it will give us some clue.

Thank you for the typo!

**Comment by smares** [comment]
It's "app". I also printed `getcwd()` and it's "/". Maybe that is the problem, it is looking for "/app" which does not exist on the filesystem. I will also try to invesigate. The app is running inside a Docker container and maybe there's something wrong with how paths are set up.

**Comment by MichaelHoste** [comment]
`getcwd()` should return `/var/www/project`, right? I don't know why it shouldn't be the case.

Are you correctly executing `php artisan translation:init` from the `/var/www/project` directory?

**Comment by smares** [comment]
OK, the problem was that I was not setting `--workdir` when calling the docker run command that executes `artisan` in the container. Problem is solved when that is used - never had to with the artisan commands I used previously.

But I have a suggestion, though: instead of hard-coding `app` and `resources` in the config and relying on the working directory, you might wand to use `app_path()` and `resource_path()` as default. Those Laravel helpers will return the correct absolute path and you don't have to call artisan inside the project root. And when users add their own directories, maybe probe them as-is plus `base_path() . $directory` as fallback.

**Comment by MichaelHoste** [comment]
I'm glad you were able to find the issue.

> But I have a suggestion, though: instead of hard-coding app and resources in the config and relying on the working directory, you might wand to use app_path() and resource_path() as default. 

You're right, we should think about doing that. However, we can't use `resource_path()` directly because of Laravel 5 compatibility.

EDIT: I'm closing the issue. BTW the typo is fixed, thank you 😄
