### ISSUE TITLE
Strings inside blade attributes not recognized

### ISSUE THREAD

**Issue by antonhedling** [translation/laravel#21]
We've encountered an issue where having a blade component with a translated string as a attribute. Example code below:

`<x-form-row :label="t('Name')"></x-form-row>`

This unfortunately won't get picked up when running the sync command. There are ways around this obviously but I just wondered if anyone has an idea on if this could be solved?

**Comment by MichaelHoste** [comment]
Hi Anton,

We depend largely on https://github.com/php-gettext/Gettext (Version 4.x) for the Blade parsing, and it seems that parsing these attributes is not supported: https://github.com/php-gettext/Gettext/issues/172

It should however be possible to write something like this and get the correct value parsed:

```blade
<x-form-row label="{{ t('Name') }}"></x-form-row>
```

The syntax is not very different.

It should also be possible to parse these values yourself (user a RegExp maybe?) and inject them like explained here: https://github.com/php-gettext/Gettext/issues/172#issuecomment-370480024

But I'm not sure dealing with all the different GetText syntaxes just for this specific case will worth it.
