### ISSUE TITLE
php artisan translation:init suceeds, php artisan translation:sync tells me to init first

### ISSUE THREAD

**Issue by sandrotanner** [translation/laravel#26]
After I init the translation (seemingly successfully, see output below), the backend still shows the "setup" page. If i try to `php artisan translation:sync` it tells me: `{"error":"This project has not been initialized yet. Please use the \"init\" operation."}` wven though I already initialized.

My translation.php
```
<?php

return [
    'key' => env('TRANSLATIONIO_KEY'),
    'source_locale' => 'de-CH',
    'target_locales' => ['fr-FR'],

    /* Directories to scan for Gettext strings */
    'gettext_parse_paths' => ['app', 'resources'],

    /* Where the Gettext translations are stored */
    'gettext_locales_path' => 'resources/lang/gettext'
];
```
The key is in my .env

How i start the initialization: `$ docker-compose exec app php artisan translation:init`

The output I get
```
Init started
Init ended with success
----------
Use this URL to translate: https://translation.io/sandrotanner/my-project-name
----------

```
Do your logs give any insight on what might go wrong? Thanks in advance :)

BTW I use Laravel 8 and the official php docker image "php:8.0-fpm"

**Comment by MichaelHoste** [comment]
Hi @sandrotanner,

The most common error at that point is that there isn't any key to initialize on your project. That's why it stays empty.

Usually it's because the source language in your config file is not the same as the one in your project (ex: "de-CH" instead of "de"?).

Would that maybe be the issue here?

**Comment by sandrotanner** [comment]
Thanks a lot! I actually had the local slightly off but that was not the problem apparently. It was (like you said) that I had no keys yet.

**Comment by MichaelHoste** [comment]
I'm glad your issue was fixed! 🙂
