### ISSUE TITLE
Creation of dynamic property Tio\Laravel\GettextTranslationSaver::$config is deprecated

### ISSUE THREAD

**Issue by Outsidaz** [translation/laravel#34]
Hi there,

I want you to notice, that on PHP 8.2 I've got a warning:

`Creation of dynamic property Tio\Laravel\GettextTranslationSaver::$config is deprecated in <...>/vendor/tio/laravel/src/GettextTranslationSaver.php on line 26`

PHP: 8.2.4
Laravel: 9.52.5

**Comment by Outsidaz** [comment]
To fix the warning, need to change the declaration of the $config property from a dynamic property to a class property.

`private array $config`

**Comment by MichaelHoste** [comment]
Thanks @Outsidaz !

We'll try to fix that soon, it seems quite easy to do.

Just so you know, we've got some weird issues between PHP 8.2 and one dependency of our test suite (cf. https://github.com/php-vcr/php-vcr/issues/373) but once it's fixed, we'll update our CI to include PHP versions > 8.1

**Comment by MichaelHoste** [comment]
> To fix the warning, need to change the declaration of the $config property from a dynamic property to a class property.
> private array $config

Thanks! That was my first impression too.
It's probably just something that we forgot, there was no reason for it to be a dynamic property.

**Comment by MichaelHoste** [comment]
We fixed the deprecation warning in the 1.23 release.
Thanks for this 🙂
