### ISSUE TITLE
Laravel 11 hasn't no lang directory by default

### ISSUE THREAD

**Issue by ruaq** [translation/laravel#36]
I've tried to initiate a new project, based on Laravel 11. The `init` command runs without error, but the project site isn't showing translations.

With a `translation:sync` I got:

```
php artisan translation:sync
Sync started

   ErrorException

  file_put_contents(C:\laragon\www\secpal\lang\.translation_io): Failed to open stream: No such file or directory

  at vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:204
    200▕      * @return int|bool
    201▕      */
    202▕     public function put($path, $contents, $lock = false)
    203▕     {
  ➜ 204▕         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    205▕     }
    206▕
    207▕     /**
    208▕      * Write the contents of a file, replacing it atomically if it already exists.

  1   vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:204

  2   vendor\tio\laravel\src\Service\SourceEditSync.php:166
      Illuminate\Filesystem\Filesystem::put("C:\laragon\www\secpal\lang\.translation_io", "{"timestamp":1715527102}")
```

The reason is, that Laravel 11 doesn't create an `lang` directory by default, anymore. I'm using `__('My Text')`, so I created/published it neither.
A `php artisan lang:publish` and another `php artisan translation:init` fixed it.

So I think, the problem isn't the Windows environment but the missing/not published lang folder.

**Comment by ruaq** [comment]
The issue was, that no translatable strings were found, without the lang folder. So it's a project and no script error. Apologies!

**Comment by MichaelHoste** [comment]
Thank you for this issue @ruaq !
We improved the README a bit so people don't forget to generate their lang directory : https://github.com/translation/laravel/pull/37
